workspace = { members = [ "src/beeker_isa", "src/chiplet_networking","src/embeddings", "src/riscv_osgui"] }
[package]
name = "riscv_chiplet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
